SELECT ALUNO.Nome
FROM ALUNO
    inner join TURMA on TURMA.aluno_id = ALUNO.id
    inner join PROFESSOR ON PROFESSOR.id = TURMA.PROFESSOR_id
WHERE PROFESSOR.nome = 'JOAO PEDRO' 


SELECT TURMA.dia_da_semana
FROM TURMA
    inner join DISCIPLINA on DISCIPLINA.ID = TURMA.DISCIPLINA_id
WHERE DISCIPLINA.nome = 'MATEMATICA'

SELECT ALUNO.Nome
from ALUNO
    inner join TURMA on TURMA.aluno_id = ALUNO.id
    inner join DISCIPLINA on DISCIPLINA.ID = TURMA.DISCIPLINA_id
where DISCIPLINA.nome in ('MATEMATICA', 'FISICA') 

SELECT DISCIPLINA.nome
from DISCIPLINA
    left join TURMA on TURMA.DISCIPLINA_id = DISCIPLINA.id
where TURMA.id is NULL 

SELECT DISTINCT ALUNO.nome
FROM ALUNO
inner join TURMA on TURMA.aluno_id = ALUNO.id
left join DISCIPLINA on DISCIPLINA.ID = TURMA.DISCIPLINA_id
where DISCIPLINA.nome = 'MATEMATICA'
    AND DISCIPLINA.nome <> 'QUIMICA' 